version: 2.1
jobs:
  run_tests:
    docker:
      -image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
                npm install --save
      - run:
          name: Run unit tests
          command: |
            ./node_modules/mocha/bin/mocha -r ts-node/register src/test/**.js

workflows:
  build_test:
    jobs:
      - run_tests